/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:417938:
  appc.background(230);
} //_CODE_:window1:417938:

public void rowChairMoved(GCustomSlider source, GEvent event) { //_CODE_:rowChairs:405974:
  //if (rowChair
} //_CODE_:rowChairs:405974:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 300, 400, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  rowChairs = new GCustomSlider(window1, 42, 44, 100, 40, "red_yellow18px");
  rowChairs.setLimits(1.0, 1.0, 10.0);
  rowChairs.setStickToTicks(true);
  rowChairs.setShowTicks(true);
  rowChairs.setNumberFormat(G4P.DECIMAL, 2);
  rowChairs.setLocalColorScheme(GCScheme.SCHEME_8);
  rowChairs.setOpaque(false);
  rowChairs.addEventHandler(this, "rowChairMoved");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GCustomSlider rowChairs; 
